[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "greatvictor.anjorin@gmail.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

[providers]
  [providers.docker]
    exposedByDefault = false

[log]
  level = "DEBUG"

[api]
  dashboard = true
  insecure = true

