[http.middlewares]
  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true

[http.routers]
  [http.routers.redirect-to-https]
    entryPoints = ["web"]
    rule = "HostRegexp(`{host:.+}`)"
    middlewares = ["https-redirect"]

